name: setup

runs:
  using: composite
  steps:
    - name: Setup NodeJS
      id: nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: npm

    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-node-modules-

    - name: Cache Hardhat artifacts
      id: cache-hardhat-artifacts
      uses: actions/cache@v3
      with:
        path: 'artifacts'
        key: ${{ runner.os }}-hardhat-artifacts-${{ hashFiles('contracts/**/*.sol') }}
        restore-keys: |
            ${{ runner.os }}-hardhat-artifacts-${{ hashFiles('contracts/**/*.sol') }}
            ${{ runner.os }}-hardhat-artifacts-

    - name: Cache Hardhat cache
      id: cache-hardhat-cache
      uses: actions/cache@v3
      with:
        path: 'cache'
        key: ${{ runner.os }}-hardhat-cache-${{ hashFiles('contracts/**/*.sol') }}
        restore-keys: |
            ${{ runner.os }}-hardhat-cache-${{ hashFiles('contracts/**/*.sol') }}
            ${{ runner.os }}-hardhat-cache-

    - name: Cache Typechain types
      id: cache-typechain-types
      uses: actions/cache@v3
      with:
        path: 'typechain'
        key: ${{ runner.os }}-typechain-types-${{ hashFiles('contracts/**/*.sol') }}
        restore-keys: |
            ${{ runner.os }}-typechain-types-${{ hashFiles('contracts/**/*.sol') }}
            ${{ runner.os }}-typechain-types-

    - if: >
        steps.cache-node-modules.outputs.cache-hit != 'true' ||
        steps.cache-hardhat-artifacts.outputs.cache-hit != 'true' ||
        steps.cache-hardhat-cache.outputs.cache-hit != 'true' ||
        steps.cache-typechain-types.outputs.cache-hit != 'true'
      name: Install dependencies & run prepare
      shell: bash
      run: npm ci
